### ISSUE TITLE
Integration with doctrine module

### ISSUE THREAD

**Issue by kr0hmy** [lorenzoferrarajr/LfjOpauth#6]
Hello!
I hope you can help me!
I'm using zf2 doctrine module authentication mechanism.
I'm trying to integrate your module into my app.
I'm not yet sure but it looks like there might be a conflit when using both.

It seems making a custom Auth Adapter for LfjOpauth which return a user entity instead of an array might be a solution. Have you got any advice on using your module with doctrine?

Thank you!

**Comment by merzh** [comment]
Hi @lorenzoferrarajr , sorry for late answer, i have checked it in my localhost, so problem not solved, to fix we need remove lines        if ($services->has('Zend\Authentication\AuthenticationService')) {
            return $services->get('Zend\Authentication\AuthenticationService');
        }
from LfjOpauth\Authentication\AuthenticationServiceFactory, thanks for work.

**Comment by lorenzoferrarajr** [comment]
Hi @merzh,
thanks for keeping up with the issue.

Could you try to define your own AuthenticationServiceFactory? You should be able to do it adding the next lines to your configuration:

```php
    'service_manager' => array(
        'factories' => array(
            'lfjopauth_auth_service' => 'My\Custom\AuthenticationServiceFactory'
        )
    ),
```

And your own custom factory class:

```php
<?php

namespace My\Custom;

use Zend\Authentication\AuthenticationService;
use Zend\ServiceManager\ServiceLocatorInterface;

class AuthenticationServiceFactory
{
    public function __invoke(ServiceLocatorInterface $services)
    {
        return new AuthenticationService();
    }
}
```

Let me know if this is a good solution.

Thanks!

**Comment by merzh** [comment]
@lorenzoferrarajr , thanks, it's solved problem

**Comment by lorenzoferrarajr** [comment]
@merzh great! Did you use a different factory for the `lfjopauth_auth_service` as I pointed out in [my previous comment](https://github.com/lorenzoferrarajr/LfjOpauth/issues/6#issuecomment-76626826)?

**Comment by merzh** [comment]
@lorenzoferrarajr , yes
